// <auto-generated />
using System;
using ForestLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForestLibrary.Migrations
{
    [DbContext(typeof(ForestContext))]
    partial class ForestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ForestLibrary.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TreeId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.HasIndex("TreeId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("ForestLibrary.Models.Forest", b =>
                {
                    b.Property<int>("ForestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForestId"));

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ForestId");

                    b.ToTable("Forests");
                });

            modelBuilder.Entity("ForestLibrary.Models.Leaf", b =>
                {
                    b.Property<int>("LeafId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeafId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeafId");

                    b.HasIndex("BranchId");

                    b.ToTable("Leaves");
                });

            modelBuilder.Entity("ForestLibrary.Models.Tree", b =>
                {
                    b.Property<int>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TreeId"));

                    b.Property<int?>("ForestId")
                        .HasColumnType("int");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TreeId");

                    b.HasIndex("ForestId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("ForestLibrary.Models.Branch", b =>
                {
                    b.HasOne("ForestLibrary.Models.Tree", "Tree")
                        .WithMany("Branches")
                        .HasForeignKey("TreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tree");
                });

            modelBuilder.Entity("ForestLibrary.Models.Leaf", b =>
                {
                    b.HasOne("ForestLibrary.Models.Branch", "Branch")
                        .WithMany("Leaves")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ForestLibrary.Models.Tree", b =>
                {
                    b.HasOne("ForestLibrary.Models.Forest", null)
                        .WithMany("Trees")
                        .HasForeignKey("ForestId");
                });

            modelBuilder.Entity("ForestLibrary.Models.Branch", b =>
                {
                    b.Navigation("Leaves");
                });

            modelBuilder.Entity("ForestLibrary.Models.Forest", b =>
                {
                    b.Navigation("Trees");
                });

            modelBuilder.Entity("ForestLibrary.Models.Tree", b =>
                {
                    b.Navigation("Branches");
                });
#pragma warning restore 612, 618
        }
    }
}
